site_name: Project PANOPTES
site_url: https://panoptes.github.io/
repo_url: https://github.com/panoptes/panoptes.github.io
repo_name: panoptes/panoptes.github.io

theme:
  name: material
  palette:
    primary: deep orange
    accent: light blue
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
